# Generated by Django 4.2.9 on 2024-01-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tname',
            field=models.CharField(max_length=250),
        ),
    ]
